<?php

namespace Landing\TemplatesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CatchEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatchEmailRepository extends EntityRepository
{
}
