<?php

namespace Landing\TemplatesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SimpleLandingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SimpleLandingRepository extends EntityRepository
{
}
